name: CI

on: [push, pull_request]

jobs:
  windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Добавлено для полного клонирования
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.10
      - name: Builder image
        env:
          TARGET_OS: Windows
        run: docker build -t electrum-wine-builder-img ./contrib/build-wine/
      - name: Compile Windows binary
        run: |
          docker run \
            --name electrum-wine-builder-cont \
            -v $PWD:/opt/wine64/drive_c/electrum \
            -v $PWD/.git:/opt/wine64/drive_c/electrum/.git:ro \
            --rm \
            --workdir /opt/wine64/drive_c/electrum/contrib/build-wine \
            electrum-wine-builder-img \
            ./make_win.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: electrum-${{ github.sha }}-windows
          path: contrib/build-wine/dist/*.exe

  appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Добавлено для полного клонирования
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.10
      - name: Builder image
        run: docker build -t electrum-appimage-builder-img ./contrib/build-linux/appimage/
      - name: Compile Linux AppImage
        run: |
          docker run \
            --name electrum-appimage-builder-cont \
            -v $PWD:/opt/electrum \
            -v $PWD/.git:/opt/electrum/.git:ro \
            --rm \
            --workdir /opt/electrum/contrib/build-linux/appimage \
            electrum-appimage-builder-img \
            ./make_appimage.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: electrum-${{ github.sha }}-appimage
          path: dist/*.AppImage

  tarball:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Добавлено для полного клонирования
      - name: Builder image
        run: docker build -t electrum-sdist-builder-img ./contrib/build-linux/sdist/
      - name: Compile Linux tarball
        run: |
          docker run \
            --name electrum-sdist-builder-cont \
            -v $PWD:/opt/electrum \
            -v $PWD/.git:/opt/electrum/.git:ro \
            --rm \
            --workdir /opt/electrum/contrib/build-linux/sdist \
            electrum-sdist-builder-img \
            ./make_sdist.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: electrum-${{ github.sha }}-tarball
          path: dist/*.tar.gz

  source-only-tarball:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Полная история git
        path: 'src'     # Отдельная директория

    - name: Verify git repository
      run: |
        ls -la src/.git
        git -C src log -1 --oneline

    - name: Builder image
      run: docker build -t electrum-source-only-tarball-builder-img ./contrib/build-linux/sdist/

    - name: Prepare git config
      run: |
        # Копируем git конфиг для использования в контейнере
        mkdir -p src/.git-container
        cp -r src/.git/* src/.git-container/
        chmod -R a+rwx src/.git-container

    - name: Compile Linux tarball
      working-directory: ./src
      run: |
        docker run \
          --name electrum-source-only-tarball-builder-cont \
          -v $PWD:/opt/electrum \
          -v $PWD/.git-container:/opt/electrum/.git:ro \
          -v $HOME/.gitconfig:/etc/gitconfig:ro \
          --rm \
          --workdir /opt/electrum/contrib/build-linux/sdist \
          --env OMIT_UNCLEAN_FILES=1 \
          electrum-source-only-tarball-builder-img \
          sh -c "git config --global --add safe.directory /opt/electrum && ./make_sdist.sh"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: electrum-${{ github.sha }}-source-only-tarball
        path: src/dist/*.tar.gz

  macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Добавлено для полного клонирования
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.10
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 14.1.0
      - name: Compile OSX dmg
        run: ./contrib/osx/make_osx.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: electrum-${{ github.sha }}-macos
          path: dist/*.dmg
