name: Build Electrum (Docker)

on:
  push:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *' # Nightly builds at 02:30 UTC

jobs:
  build-windows:
    name: "Build Windows (Docker)"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Build Windows installer
      uses: docker/build-push-action@v5
      with:
        context: ./contrib/build-wine
        tags: electrum-wine-builder
        load: true
        
    - name: Run Windows build script
      run: |
        docker run --rm -v $PWD:/opt/wine64/drive_c/electrum \
          -v $PWD/.git:/opt/wine64/drive_c/electrum/.git \
          -e CIRRUS_TASK_NAME=build-windows \
          electrum-wine-builder \
          /bin/bash -c "cd /opt/wine64/drive_c/electrum/contrib/build-wine && ./make_win.sh"
          
    - uses: actions/upload-artifact@v4
      with:
        name: electrum-windows
        path: contrib/build-wine/dist/*

  build-appimage:
    name: "Build Linux AppImage (Docker)"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Build AppImage builder
      uses: docker/build-push-action@v5
      with:
        context: ./contrib/build-linux/appimage
        tags: electrum-appimage-builder
        load: true
        
    - name: Run AppImage build script
      run: |
        docker run --rm -v $PWD:/opt/electrum \
          -v $PWD/.git:/opt/electrum/.git \
          electrum-appimage-builder \
          /bin/bash -c "cd /opt/electrum && ./contrib/build-linux/appimage/make_appimage.sh"
          
    - uses: actions/upload-artifact@v4
      with:
        name: electrum-appimage
        path: dist/*.AppImage

 
