name: Build Electrum (Docker)

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-appimage:
    name: "Build AppImage"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0  # Полная git история
        
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./contrib/build-linux/appimage
        tags: electrum-appimage-builder
        load: true
        
    - name: Prepare build context
      run: |
        # Создаем временную директорию с полной git историей
        mkdir -p /tmp/electrum-build
        git clone --depth 1 --no-single-branch file://$PWD /tmp/electrum-build
        cd /tmp/electrum-build
        git submodule update --init --recursive
        
    - name: Run AppImage build
      run: |
        docker run --rm -v /tmp/electrum-build:/opt/electrum \
          -v /tmp/electrum-build/.git:/opt/electrum/.git \
          electrum-appimage-builder \
          /bin/bash -c "cd /opt/electrum && ./contrib/build-linux/appimage/make_appimage.sh"
          
    - name: Copy artifacts
      run: |
        cp -r /tmp/electrum-build/dist $PWD/
        
    - uses: actions/upload-artifact@v4
      with:
        name: electrum-appimage
        path: dist/*.AppImage
