name: Build Electrum AppImage

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-appimage:
    name: "Build AppImage"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./contrib/build-linux/appimage
        tags: electrum-appimage-builder
        load: true
        
    - name: Run build in container
      run: |
        # Создаем временный git bundle
        git bundle create /tmp/electrum.bundle --all
        
        # Создаем временную директорию
        mkdir -p /tmp/electrum-build
        cd /tmp/electrum-build
        
        # Клонируем из bundle
        git clone --depth 1 file:///tmp/electrum.bundle .
        git submodule update --init --recursive
        
        # Запускаем сборку
        docker run --rm \
          -v /tmp/electrum-build:/opt/electrum \
          -v /tmp/electrum-build/.git:/opt/electrum/.git \
          -v /tmp/electrum-build/.git/modules:/opt/electrum/.git/modules \
          electrum-appimage-builder \
          /bin/bash -c "cd /opt/electrum && ./contrib/build-linux/appimage/make_appimage.sh"
        
        # Копируем артефакты
        cp -r /tmp/electrum-build/dist $PWD/
        
    - uses: actions/upload-artifact@v4
      with:
        name: electrum-appimage
        path: dist/*.AppImage
