name: Build Electrum

on:
  push:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *' # Nightly builds at 02:30 UTC

env:
  PYTHON_VERSION: '3.10'
  PIP_VERSION: '23.3.1'
  PYINSTALLER_VERSION: '6.0.0'

jobs:
  build-windows:
    name: "Build Windows"
    runs-on: windows-2022
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip==${{ env.PIP_VERSION }}
        pip install -r contrib/requirements/requirements.txt
        pip install -r contrib/requirements/requirements-hw.txt
        pip install pyinstaller==${{ env.PYINSTALLER_VERSION }}
        
    - name: Build Windows installer
      run: |
        python contrib/make_packages
        python contrib/make_locale
        pyinstaller --clean -y contrib/build-wine/electrum.spec
        
    - uses: actions/upload-artifact@v4
      with:
        name: electrum-windows
        path: dist/electrum

  build-appimage:
    name: "Build Linux AppImage"
    runs-on: ubuntu-22.04
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libsecp256k1-dev \
          libzbar-dev \
          libssl-dev \
          gettext \
          zlib1g-dev \
          libgl1 \
          libegl1 \
          libxkbcommon0 \
          libdbus-1-3
        python -m pip install --upgrade pip==${{ env.PIP_VERSION }}
        pip install -r contrib/requirements/requirements.txt
        pip install -r contrib/requirements/requirements-hw.txt
        pip install pyinstaller==${{ env.PYINSTALLER_VERSION }}
        
    - name: Build AppImage
      run: |
        ./contrib/make_packages
        ./contrib/make_locale
        ./contrib/build-linux/appimage/make_appimage.sh
        
    - uses: actions/upload-artifact@v4
      with:
        name: electrum-appimage
        path: dist/*.AppImage

  build-android:
    name: "Build Android (arm64-v8a)"
    runs-on: ubuntu-22.04
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zlib1g-dev \
          openjdk-11-jdk \
          android-sdk
        python -m pip install --upgrade pip==${{ env.PIP_VERSION }}
        pip install -r contrib/requirements/requirements.txt
        pip install -r contrib/deterministic-build/requirements-android-build.txt
        
    - name: Build APK
      run: |
        ./contrib/android/make_apk qml arm64-v8a debug
        
    - uses: actions/upload-artifact@v4
      with:
        name: electrum-android
        path: dist/*.apk
